pipeline {
    agent any

    environment {
        AWS_REGION = 'ap-south-1'
        ECR_REPO = '090597375004.dkr.ecr.ap-south-1.amazonaws.com/cloud-devops-app'
        EKS_CLUSTER = 'cloud-devops-cluster'
        IMAGE_TAG = "build-${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/aasemboghani-dev/CloudDevOpsProject.git'
            }
        }

        stage('Docker Build') {
            steps {
                dir('application') {
                    sh 'docker build -t cloud-devops-app:$IMAGE_TAG .'
                }
            }
        }

        stage('Docker Test') {
            steps {
                sh 'docker images cloud-devops-app'
            }
        }

        stage('ECR Login') {
            steps {
                sh '''
                    aws ecr get-login-password --region $AWS_REGION | \
                    docker login --username AWS --password-stdin $ECR_REPO
                '''
            }
        }

        stage('Docker Push') {
            steps {
                sh '''
                    docker tag cloud-devops-app:$IMAGE_TAG $ECR_REPO:$IMAGE_TAG
                    docker push $ECR_REPO:$IMAGE_TAG
                '''
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh '''
                    aws eks update-kubeconfig \
                        --region $AWS_REGION \
                        --name $EKS_CLUSTER

                    kubectl apply -f kubernetes/deployment.yaml

                    kubectl set image deployment/cloud-devops-app \
                        cloud-devops-app=$ECR_REPO:$IMAGE_TAG

                    kubectl rollout status deployment/cloud-devops-app
                '''
            }
        }

       stage('Application Test') {
    steps {
        sh '''
            echo "Checking Kubernetes deployment..."
            kubectl rollout status deployment/cloud-devops-app

            echo "Checking pods..."
            kubectl get pods -l app=cloud-devops-app

            echo "Checking service..."
            kubectl get service cloud-devops-service

            echo "Testing application health..."
            kubectl run health-test-$BUILD_NUMBER \
                --rm \
                --restart=Never \
                --image=curlimages/curl:8.10.1 \
                -- curl -f http://cloud-devops-service/health

            echo "Application health check PASSED"
                '''
            }
        }
    }
}