pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/aasemboghani-dev/CloudDevOpsProject.git'
            }
        }

        stage('Docker Build') {
            steps {
                dir('application') {
                    sh 'docker build -t cloud-devops-app:latest .'
                }
            }
        }

        stage('Docker Test') {
            steps {
                sh 'docker images cloud-devops-app'
            }
        }
    }
}